### ISSUE TITLE
Remove Standalone Build System

### ISSUE THREAD

**Issue by ichrispa** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#18]
Since most features are now up and running, we should begin "Freezing" our project into the ChimeraTK Build System. To that End:

- [ ]  Remove the dependency projects (DeviceAccess, ControlSystemCore)
  - [ ] Build a parent project that does not require system-wide installation of all components for a build (not part of ChimeraTK, use own repo)
- [x] Modify the open62541 build for static linkage

That way, we will be able to compile the project as a ChimeraTK component and be on our way for the final release.

**Comment by mhier** [comment]
The latest two commits on github in open62541 (2cabd7c and 58ce90e) introduce a proper versioning of the .so files of open62541. We could make use of this instead of moving to static linkage, if this seems easier.

An advantage would be that this can help avoiding conflicts between different versions of the stack when using it twice in the same application (example: besides the OPC-UA-Adapter we might introduce an OPC-UA-Backend for DeviceAccess at some point). Those conflicts are probably easier avoided if open62541 is used as an external dependency which is installed independently (which kind of implies using shared libraries).

By default it seems that linking a shared library against a static library basically just makes the symbols from the static library part of the shared library, with all consequences. This means, if a symbol coming from the static library is already present at runtime, even the shared library's code linked against the static library will use the symbol which is already there. This can cause strange effects and segfaults etc., if the two versions of the stack are not binary compatible.

This does not change if linking against a shared library, but it can be dealt with, if the stack is coming from a system installation and all libraries can be linked against the same version of the stack. This will be difficult to achieve, if the stack is built as an internal dependency of the OPC-UA-Adapter.

Thus, if there is no solution for this problem, I would still vote for moving also the open62541 dependency out of this project.

PS: We at DESY have dealt with this type of problems a lot, since basically all releases of the ChimeraTK libraries and also of the DOOCS libraries are not binary compatible with the previous versions (only API compatibility is achieved). For the Debian packages, the DebianPackagingScripts help a lot mitigating these problems. I suggest we should try using these tools also for the OPC-UA-Adapter.

**Comment by ichrispa** [comment]
We are able to build in the context of ChimeraTK; the standalone build system is largely superceded.
