### ISSUE TITLE
Server crash possibly related to the OPC-UA-Adapter

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#28]
During out latest test we saw server crashes that are most likely caused by the OPC-UA-Adapter. So far we have not investigated how to trigger such a crash. 

 I hope the following traces give you an idea what happened and they have the same source.

[crash_backtrace1.txt](https://github.com/ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter/files/1789386/crash_backtrace1.txt)
[crash_backtrace2.txt](https://github.com/ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter/files/1789387/crash_backtrace2.txt)

.

**Comment by ichrispa** [comment]
Both backtraces show the exception occuring after a call to libllrfserverlib.so. 
'''
Error in `llrfserver': corrupted double-linked list: 0x00007f0a00011780 ***
'''

It is true that the OPC UA Adapter is the caller of the function, but not the location/causer of the crash.

My guess is that either someone has changed the ControlSystemAdapter or has changed something in regard to how boost handles lists. There is always the remote chance that this this is an hereforth unknown error that we simply did not cover in our testcases.

In any case: Please investigate where the list corruption is occuring, which list is affected and whose code is managing this list.

(How) Can we reliably replicate this error?

**Comment by mhier** [comment]
Actually, I think the stack trace may be a bit misleading. It is true, there is a call from _ZN18ua_processvariable21getValue_Array_doubleEv to _ZNSt6vectorIdSaIdEEaSERKS1, where the latter symbol resides in _ZNSt6vectorIdSaIdEEaSERKS1. Still it is not something which actually comes from the application side. This is merely a symbol of std::vector which presumably is used by both the OPC UA adapter and the application and by chance the version provided by the application's so file is being used. There is therefore no indication at this time that the application has part in this crash. On the other hand, we can never exclude that the cause for the crash is in a complete different place...

My understanding is that the crash is happening somewhere in the instantiation of the CREATE_READ_FUNCTION_ARRAY macro in ua_processvariable.cpp for the type double.

It is unfortunately hard to reproduce the crash, since it happened only a few times during our tests. Maybe the HZDR colleagues can somehow reproduce it when running the server for a while and clicking some stuff?

Maybe we should write some stress test reading and writing variables frequently from/to the application through the OPC UA interface. Is there e.g. an easy-to-use Python OPC UA client interface you could recommend for this purpose?

**Comment by zenker** [comment]
Yet another crash today after approx. 20min client interaction (me playing with the llrfserver) with the server. This time libllrf is not involved in any way, which supports the arguments of @mhier 's in the previous comment.

[crash_backtrace3.txt](https://github.com/ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter/files/1860131/crash_backtrace3.txt)

**Comment by zenker** [comment]
Finally I found the CoreDumps that were stored by apport. After extracting the core dumps I run gdb and I got some more detailed information. 
[crash_backtrace3_details.txt](https://github.com/ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter/files/1860338/crash_backtrace3_details.txt)
Meanwhile also the watchdog crashed and the backtrace is more clear and ends with `UA_MoniteredItem_SampleCallback ()`, which is also involved in all other crashes:
[crach_backtrace4.txt](https://github.com/ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter/files/1860346/crach_backtrace4.txt)

**Comment by zenker** [comment]
Yesterday we started a simple test. Our LabView client was changing tabs of the panel every 1.5s. This results in subscribing and unsubscribing variables every time the tab is  changed. After 6h the server crashed with a similar backtrace as posted above. No further interaction with the server was done during those 6h. Might this hint to a problem with the open62541 stack itself , since `UA_MoniteredItem_SampleCallback ()` is a function of the stack?

**Comment by zenker** [comment]
This is not observed any more since quite some time.
