### ISSUE TITLE
No OPC-UA communication possible any more after some time

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#29]
At some point the client panels lost connection to our server. This is detected by reading the CurrentTime of the ServerStatus provided by every OPC-UA server. After this event it was not possible to connect to the server any more by any client (we tried different clients, i.e. UA Expert and LabView). The server was still working. Looking at the Server process, one thread showed a very high cpu load (130%) compared to all other threads of the server. We stopped that thread and the backtrace is shown below.
[stacktrace-server-hanging.txt](https://github.com/ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter/files/1789426/stacktrace-server-hanging.txt)

Maybe this connected to the problem reported here #28 
At the time the connection was lost a client reading many variables was connected to the server, which included long data arrays. The problem occurred multiple times and could  be _solved_ only by restarting the server.

**Comment by ichrispa** [comment]
Not related to #28; What signal did you send the server? 

''
#0  0x00007f2e27fef5d3 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f2e2bfa2402 in ?? ()
''

This indicates a problem with the sockets select() call - clearly if select throws an error/hangs this is outside the scope of OPC UA itself. 

Did you compile the server against a different version of glibc than you are running the server on!? Have you tried compiling the binary directly on the given host and checking if the error still exists?

**Comment by mhier** [comment]
Everything we have used in the tests is packaged in Debian packages which have been built for specifically the Linux version we were running the application on (Ubuntu 16.04), this excludes mixing libc versions (at least if we trust the Debian packaging system and the Ubuntu maintainers not to do mad things).

We didn't send any signal to the server, at least not intentionally, but you can never really exclude that something is sending a signal (example: SIGWINCH is sent when resizing the terminal the server is running in, or SIGALARM might be sent if the application would use an alarm clock - which it doesn't to my knowledge).

If those signals would present a problem, I would call this a bug (in the stack in this case?), since they can be detected (select() returns -1 and errno is set to EINTR). If needed, signals could even be masked by using pselect() instead of select().

One way or the other: please note that the stack trace provided is a random snapshot of the process showing high CPU load. I would guess that this means that select() was not blocking indefinitely (otherwise CPU load would be 0 for this thread). This also means that the problem might not be linked to select() at all and this is merely the function call this thread stays the longest time in.

**Comment by zenker** [comment]
I'm not sending signals to the processes controlled by the watchdog. I'm just handling signals from the controlled process, i.e. SIGCHLD to avoid zombie processes. 

I will do some tests to reproduce the behaviour on our new server (with glib2.0 version 2.48.2-0ubuntu1 instead of 2.48.1-1~ubuntu16.04.1 as used during the last tests). 

If I can reproduce the problem I can try again without starting the server using the watchdog in order to exclude a possible problem introduced by the watchdog.

**Comment by zenker** [comment]
This is not observed any more since quite some time.
